fail_fast: false
repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.1.1
  hooks:
  - id: pylint
    args: [--rcfile=./.pylintrc]
    additional_dependencies: [pytest, wired, zope.interface]
